version: '3'
services:
  report-cassandra:
    image: cassandra:3.11.5
    # volumes:
    #     - ~/volumes/jhipster/report/cassandra/:/var/lib/cassandra/data
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
  # report-cassandra-migration:
  #   extends:
  #     file: cassandra-migration.yml
  #     service: report-cassandra-migration
  #   environment:
  #     - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
